# Generated by Django 6.0.6 on 2026-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='usuario probado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'intento de login',
                'verbose_name_plural': 'intentos de login',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='accounts_lo_ip_addr_71e387_idx')],
            },
        ),
    ]
