# Generated by Django 6.0.6 on 2026-07-13 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('service_interest', models.CharField(blank=True, max_length=60, verbose_name='servicio de interés')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
