# Generated by Django 6.0.6 on 2026-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='user agent'),
        ),
    ]
