# Generated by Django 6.0.6 on 2026-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_lead_ip_address_lead_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='webhook_delivered_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que n8n confirmó la recepción del lead.', null=True, verbose_name='enviado a n8n'),
        ),
    ]
