# Generated by Django 6.0.6 on 2026-09-27 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_lead_webhook_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='inicio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='último mensaje')),
            ],
            options={
                'verbose_name': 'conversación del chat',
                'verbose_name_plural': 'conversaciones del chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'visitante'), ('assistant', 'asistente')], max_length=10, verbose_name='autor')),
                ('text', models.TextField(verbose_name='texto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='landing.chatconversation', verbose_name='conversación')),
            ],
            options={
                'verbose_name': 'mensaje del chat',
                'verbose_name_plural': 'mensajes del chat',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='landing_cha_ip_addr_a4065d_idx')],
            },
        ),
    ]
