# Generated by Django 6.0.6 on 2026-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_preference',
            field=models.CharField(blank=True, max_length=20, verbose_name='preferencia de contacto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.CharField(blank=True, max_length=60, verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('landing', 'landing'), ('contacto', 'página de contacto')], default='landing', max_length=20, verbose_name='origen'),
        ),
    ]
